### ISSUE TITLE
[EPIC] Implement an CQRS-Lite architecture

### ISSUE THREAD

**Issue by edwinkortman** [corgibytes/freshli-cli#135]
# What's this?

One of the struggles we noticed when building the CycloneDX-based pipeline is scalability. Our original plan was to let a command spawn x amount of workers for another command. In practice, though, this is not working out as intended. We want to limit the number of workers spawned to whatever value passed as the argument, but if one command generates another command that also has a worker, they will multiply. 

After some discussion, we decided to try out an architecture loosely based on CQRS: 
https://www.eventstore.com/cqrs-pattern
https://matthiasnoback.nl/2015/01/a-wave-of-command-buses/
https://matthiasnoback.nl/2015/01/some-questions-about-the-command-bus/

# The Architecture
We can re-use much of the internal commands described in #55 but they'll need a small refactor to be able to work with a message bus. First let's dive into what it means.

With this setup instead of having Freshli CLI commands call other commands as if it were a CLI application calling another CLI application, we'll change this to, eventually, asynchronous message bus. The benefits of this setup is that we'll have an easier time scaling it horizontally because we can add more workers processing the messages. A downside is that we'll add a bunch of classes to make things work. 

**What are we going to add?**

We can make a distinction between four types of objects. Messages, Message Handlers, Events, and Event Subscribers. Another name for Message is Command but there's a clash with CLI commands, and it's runners. To avoid this we'll stick to messages. A message is a short "do this" statement. We'll get to the examples soon, so bear with me for now. This message only contains the necessary information for the Handler to do it's job. Think of just passing primitive types, and identifiers. At no point do you want to put an entire Order object into this. This is because the messages get send to the queue, and passing the queue a wall of text is going to slow things down or block the stream entirely. 

So we now have two types of objects. Message and Message Handler. These are connected, and there's only ever one handler for a particular message. An example:

```
class SetOrderToPaidMessage
{
      public OrderId orderId;
      public DateTime paidAt;
}
```

```
class SetOrderToPaidMessageHandler
{
    public __invoke(SetOrderToPaidMessage $message) 
    {
         // Do things
    }
}
```

**How are they connected?**

We'll be running workers. These workers sole responsibility is to offer messages from the message bus to the handlers. The handlers will then let the workers know if they can or cannot process the message. 

**What about Events?**

Events and their Subscribers are the other classes. If a Message is a way for saying "do this" then Events is a way of saying "this has happened". A subscriber can react to that. For every Event, there could be zero, one or multiple subscribers. A subscriber can't change anything in the system but it can issue a new Message to start doing something.

```
class OrderWasPaidEvent
{
      public OrderId orderId;
}
```

```
class SendEmailToUserSubscriber
{
    public __invoke(OrderWasPaidEvent $event) 
    {
         // Add message to message bus for sending email to user
    }
}
```

### In abstract terms this is how it works

[https://user-images.githubusercontent.com/7047894/179749440-be839527-ef14-4f0e-9dd0-dbd563c0daaf.png](https://user-images.githubusercontent.com/7047894/179749440-be839527-ef14-4f0e-9dd0-dbd563c0daaf.png)

### In actual terms this is how it works

[https://user-images.githubusercontent.com/7047894/180735243-d2935172-6f51-4658-8cb3-0350e2f5adc7.png](https://user-images.githubusercontent.com/7047894/180735243-d2935172-6f51-4658-8cb3-0350e2f5adc7.png)

## The entire flow then becomes

[https://user-images.githubusercontent.com/7047894/181716456-17413f4f-bbbb-4f21-9ff3-733f95e1bd4a.png](https://user-images.githubusercontent.com/7047894/181716456-17413f4f-bbbb-4f21-9ff3-733f95e1bd4a.png)

# Connected issues
- [x] #137
- [x] #146
- [x] #147
- [x] #148
- [x] #149
- [x] #150
- [x] #151
- [x] #152
- [x] #153
- [x] #205
- [x] #208 
- [x] #237
- [x] #238 
- [x] #239

**Comment by edwinkortman** [comment]
Cross-posting from #55 

```mermaid
flowchart
subgraph flow
  A[Command] --> B[Command handler] --> C(Event) --> D(Event Listener) --> A[Command]
end
```

Some rules to this flow:
- A command is just an data object, containing enough information for the handler to do it's job. Typically objects with a small foot print, so just identifiers, and primitive types.
- Handlers can scale horizontally. I could have x workers running handlers to process commands, if one command fails to be processed the others should be able to continue.
- Events are like commands, data objects. 
- Event listeners can spawn a command. It cannot start doing stuff other than that.

```mermaid
flowchart TD
subgraph git

  cloneGitCommand[Clone Git Repository: command] --> 
  cloneGitEvent(Git Repository Was Cloned: event) -->
  computeHistoryCommand[Compute History: command] --> 
  |For each point in history found|pointInGitHistoryFound(Point in Git history found: event) -->
  checkoutHistory[Check out history: command]
end
```

### What a command would look like

```php
final class ComputeHistory 
{
      private RepositoryId $repositoryId; 
      public __construct(RepositoryId $repositoryId) 
      {
            $this->repositoryId = $repositoryId;
      }

      public function repositoryId()
      {
            return $this->repositoryId;
      }
}
```

### What an Event would look like
Similar to the Command but the class name is different. It's describing something that has happened instead of describing something you want to make happen.

```php
final class HistoryWasComputed 
{
      private GitCommitId $commitId; 

      public __construct(GitCommitId $commitId) 
      {
            $this->commitId = $commitId;
      }

      public function commitId()
      {
            return $this->commitId;
      }
}
```

### What a Listener would look like

```php
final class HistoryWasComputedListener
{
      public function __invoke(HistoryWasComputed $event)
     {
            $this->commandBus->create(
                  new CheckoutHistoryCommand($event->commitId())
            );
     }
}
```

### What a Command Handler would look like

```php
final class CheckoutHistoryHandler
{
      public function handle(CheckoutHistoryCommand $command)
     {
            // Do the actual handling of stuff so in this example. Checkout the history for a given git commit id. 
     }
}
```



### How does this scale horizontally

Given a subsection of the graph above.

```mermaid
flowchart TD
subgraph git

  computeHistoryCommand[Compute History: command] --> 
  computeHistoryCommandHandler[Compute History: command handler] -->
  pointInGitHistoryFound(Point in Git history found: event) -->
  pointInGitHistoryFoundListener(Point in git history found: event listener) -->
  checkoutHistory[Check out history: command]
end
```

Some terminology:
Worker: a process that's delivering commands to their respective handler.

When you compute the history for a repository, you get back a list of all the interesting points in a repositories' history. For each history we want to checkout the files on to the file system. This can be done in parallel as we aren't working in a shared directory. We are creating an archive into a new directory. So we could have x amount of workers running to do the actual checking out of the history. 

What you want to avoid with this structure is having command handlers manipulate the same thing, but in theory that's unlikely to happen because of the way they are set up. You are only doing something else after something has already happened.

**Comment by edwinkortman** [comment]
## Events not (yet?) dispatching new activities

### Crucial to functioning happy path
- `GitRepositoryClonedEvent` dispatch `ComputeHistoryActivity`: https://github.com/corgibytes/freshli-cli/issues/205
- `HistoryIntervalStopFoundEvent` dispatch `CheckoutHistoryActivity`: https://github.com/corgibytes/freshli-cli/issues/208
- `HistoryStopCheckedOutEvent` dispatch `DetectAgentsForDetectManifestsActivity`: https://github.com/corgibytes/freshli-cli/issues/237
- `ManifestDetectedEvent` dispatch `GenerateBillOfMaterialsActivity`: https://github.com/corgibytes/freshli-cli/issues/238
- `BillOfMaterialsGeneratedEvent` dispatch `ComputeLibYearActivity`: https://github.com/corgibytes/freshli-cli/issues/239
- `LibYearComputedEvent` dispatch ???


### Failures, errors
- `CacheDestroyFailedEvent`
- `CloneGitRepositoryFailedEvent`

### Clean-up after analysis
- `CacheDestroyedEvent`

### Unknown
- `AgentsDetectedEvent`

**Comment by edwinkortman** [comment]
![image](https://user-images.githubusercontent.com/7047894/189331880-6fea876f-3c73-4970-9985-2b92dc12dcee.png)

**Comment by mscottford** [comment]
I updated the task list in the description to include the additional issue numbers.
