### ISSUE TITLE
Clean up README file and NuGet

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#226]
After #225 is merged, the Docker image published on DockerHub will be the preferred way to run `freshli`. All references to using the `dotnet tool` installer should be removed.

- [x] Add instructions to README for running `freshli` with the [`corgibytes/freshli-cli` container](https://hub.docker.com/repository/docker/corgibytes/freshli-cli)
- [x] Remove instructions for installing/using `dotnet tool` version of `freshli`
- [x] Remove steps from `ci.yml` for build/uploading NuGet packages
- [x] If possible, add a note to the [old NuGet package page](https://www.nuget.org/packages/Corgibytes.Freshli.Cli) that newer versions of `freshli` are installed differently
- [x] Update `ci.yml` so that the release notes include the "long" image id of the Docker container image that's associated with the release

**Comment by edwinkortman** [comment]
@mscottford The API key in our password manager has expired so I can't update the note. Could you add me to https://www.nuget.org/profiles/corgibytes so I can try to update it.

Note for myself:

Check if .csproj needs these lines:
```xml
    <FileVersion>0.4.1</FileVersion>
    <VersionPrefix>0.4.1</VersionPrefix>
```

```bash
dotnet pack
dotnet nuget push Corgibytes.Freshli.Cli/bin/Debug/Corgibytes.Freshli.Cli.0.4.1.nupkg --api-key=$API_KEY --source https://api.nuget.org/v3/index.json
```
