### ISSUE TITLE
Fix failing CI on `main` branch

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#227]
CI is failing on `main` when changes are made and then committed to the repository. This is because the main branch is marked as "protected". We need to find a way to bypass the protection from the GitHub action or we need to turn off the protection.

**Comment by steverichey** [comment]
How about another method to generate the changelog? I think branch protection is a good idea, and I don't think we want an exception to branch protection for a bot.

**Comment by edwinkortman** [comment]
I think we should make an exception for the bot. For me not to allow a bot to avoid branch protection would be in cases where we'd do big commits like linters auto-committing or anything alike. In this case, it's making entries to the changelog.md and the GitHub action we are using is well supported:

https://github.blog/2020-09-17-github-action-hero-stefan-zweifel-and-git-auto-commit/
https://github.com/stefanzweifel/git-auto-commit-action/pulls?q=is%3Aopen+is%3Apr

@steverichey You said you think we shouldn't make an exception. Could you elaborate why not?

**Comment by mscottford** [comment]
I also feel like an exception is warranted in this case.
