### ISSUE TITLE
Add option to `analyze` command so that it does not collect historical metrics

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#234]
The `--latest-only` option changes the behavior of the latest command so that it doesn't walk the git history for the provided repository and branch. This option is incompatible with the `--include-history` and `--history-interval` options.

We should also permit analyzing a codebase that has already been checked out (should that be a separate issue?). This is done by providing a path, such as `~/code/project` instead of a url for a Git repository. When analyzing a local directory, if `--latest-only` is provided, then it is permissible for the local directory to contain changed files. Otherwise, a clean working directory is required.

We should also permit appending the data collected to a previous set of analysis results with the `--analysis-results-id` option. Make this option only allowed when `--latest-only` is specified.

**Comment by edwinkortman** [comment]
> We should also permit analyzing a codebase that has already been checked out (should that be a separate issue?)
Yes, I think it should because that would mean finding a way around all the git clone stuff. I've added #287 for it :D
