### ISSUE TITLE
Add `cache prepare` command

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#49]
## `cache prepare`

Used to ensure that the cache directory exists and that it contains a valid cache database instance. If an existing cache database is found, then the database will be checked to determine if migrations need to be run against it.

```
freshli [global options] cache prepare
```

**What this command does?**

Ensures that the cache directory exists and that the database that it contains is valid and up-to-date.

Global Otions

- `--cache-dir <path>`
    - the location where the `freshli` command will write temporary files as part of it’s processing
    - default value: `$HOME/.freshli`

**Comment by CodeMouse92** [comment]
We will use [Entity Framework Core 6.0](https://docs.microsoft.com/en-us/ef/core/)

* valid = we can open a connection to the SQLite database
* up-to-date = no pending migrations to run

The `cache destroy` command will clean up the temporary files.

**Comment by CodeMouse92** [comment]
- [ ] Implement `cache` command.
- [ ] Implement `prepare` subcommand.
- [ ] Implement `--cache-dir` global option.
- [ ] Write acceptance tests.

**Comment by CodeMouse92** [comment]
For reference: https://dotnetcoretutorials.com/2020/10/06/running-efcore-migrations-from-your-own-code/
