### ISSUE TITLE
Add `git compute-history` command

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#52]
## `git compute-history`

Used to examine the history of the specified repository and determine the sha hashes that will need to be checked out to complete a historical analysis at the intervals specified.

```
freshli [global options] git compute-history [command options] <respository-id>
```

**What this command does?**

Creates a row in the repository_histories table for each history interval stop and records the sha hash that is detected for that point in time. Each date/time and sha hash pair is also output to STDOUT on a single line per row.

Global Options

- `--cache-dir <path>`
    - the location where the `freshli` command will write temporary files as part of it’s processing
    - default value: `$HOME/.freshli`

Command Options

- `--git-path`
    - Path to the `git` binary
    - default value: `git`
   
- `--commit-history`
    - Analyzes only the points in time when files have changed in the commit history. This can be combined with `--history-invertal` to make sure that every commit is included in the result set. If `--history-interval` is not used, then only the values from each commit will be present in the output, meaning that the data will show the metrics at the time that the files were changed, but will not show how the metrics changed between commits.
- `--history-interval <duration>`
    - As the `analyze` command moves backwards in time through the history of the project, what time interval should it use to determine the points in time that are sampled
    - default value: `1m`
    - valid values: `/\d+[ymwd]?/`
        - `y` suffix – specifies duration in years
        - `m` suffix – specifies duration in months
        - `w` suffix – specifies duration in weeks
        - `d` suffix – specifies duration in days
        - If no suffix is provided, then the duration is assumed to be a number of months
    - When walking backward in time the following approach will be taken: given current time `T`, subtract the smallest amount of time to produce time `T'` such that `T'` when be an even interval of the specified duration suffix.
        - Example:
            - Assume
                - `T = 2022-02-01 23:11:43Z`
                - Interval duration — `1d`
                - Timezone offset — `-04:00`
                - Then `T'` would be set to `2022-02-01 00:00:00-04:00`
                - The value of `T'` would be decremented by one calendar day until the earliest commit date is reached

**Comment by edwinkortman** [comment]
@mscottford How do you want to pick the correct commits? I've made some tables to what I think but does that match what you thought? In a nutshell: it's pick the last commit available for a specific interval.

## Given duration is days
Marked are the relevant changes related to the row above.
Itt should always pick the last commit of a day

| Sha (created at)                    | Should be listed |
|---|:---:|
| 8d6aea (2022-01-01 10:30) |   | 
| 49a648 (2022-01-01 **21:30**) | :heavy_check_mark:  | 
| ca6533 (2022-01-**02** 09:45) |  :heavy_check_mark:  | 
| 562c46 (2023-**02-07** 4:30) | :heavy_check_mark:  | 

## Given duration is Weeks
Marked are the relevant changes related to the row above.
It should always pick the last commit of a week.

| Sha (created at)                    | Weekday | Should be listed |
|---|:---:|:---:|
| 8d6aea (2022-01-01 10:30) |  Saturday | :heavy_check_mark: | 
| 49a648 (2022-01-**03** 21:30) | Monday  | :heavy_check_mark: | 
| ca6533 (2022-01-10 09:45) |  Monday | | 
| 562c46 (2023-01-**11** 4:30) | Tuesday  | |
| 7c802a (2022-01-**14** 10:30) | Friday  | :heavy_check_mark: | 


## Given duration is months
Marked are the relevant changes related to the row above.
It should always pick the last commit of a month.

| Sha (created at)                    | Should be listed |
|---|:---:|
| 8d6aea (2022-01-01 10:30) |  | 
| 49a648 (2022-01-01 21:30) |  | 
| ca6533 (2022-01-**29** 09:45) |  :heavy_check_mark:  | 
| 562c46 (2023-**02-07** 4:30) | :heavy_check_mark:  | 


## Given duration is years
Marked are the relevant changes related to the row above.
It should always pick the last commit of a year.

| Sha (created at)                    | Should be listed |
|---|:---:|
| 8d6aea (2022-01-01 10:30) |  | 
| 49a648 (2022-01-01 21:30) |  | 
| ca6533 (2022-**12-31** 09:45) |  :heavy_check_mark:  | 
| 562c46 (**2023**-02-07 4:30) | :heavy_check_mark:  |

**Comment by mscottford** [comment]
But in general, "pick the most recent commit in the given interval" should be the way to go.

M. Scott Ford
Co-Founder & Chief Code Whisperer (CTO)
Corgibytes, LLC
804.596.2375 x701
pronouns: he/him
***@***.***
https://corgibytes.com ( https://corgibytes.com/ )

Have you read our First Round Review ( http://firstround.com/review/forget-technical-debt-heres-how-to-build-technical-wealth/ ) article about paying off technical debt?

Love refactoring and TDD? Join us at LegacyCode.Rocks ( http://LegacyCode.Rocks ) for virtual meetups, podcasts, and more.

Sent via Superhuman ( ***@***.*** )
