### ISSUE TITLE
[EPIC] Implement CycloneDX-based pipeline

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#55]
# What’s this?

A re-imagining of Freshli that takes advantage of the ecosystem of tools that generate CycloneDX BOM files. The current idea is to drive this from the Freshli CLI.

# Architecture

The CLI is going to be split into user-facing commands and internal commands. This is similar to the approach that’s taken by the `git` set of tools. In that ecosystem, there are a set of commands that are meant to be user-facing (called porcelain commands), and there are other commands that are in support of internal operations and other commands (called plumbing commands).

We’ll do our best to follow the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) for building out these commands:

- Do one thing, and do it well
- The output of each command can be used as input for another command, with the ability to read information from STDIN and write information to STDOUT - sometimes this point will be deviated from when it makes more sense to persist output to the file system so that it can be used by multiple programs reading the same information at the same time

One reason for taking this approach is that it allows us to use the operating system’s process scheduling to get parallelization of activities. Another reason is that it allows us to interact with tools that we did not write, such as `git` for source code integration or `mvn` for build system integration or a command line tool that knows how to generate or manipulate CycloneDX BOM files. 

It’s expected that many of the commands below will permit running multiple workers, with work to be completed stored in queue tables in the local database. The local database will also be used to cache information from various external sources and to cache the results of expensive computations.

One goal with caching is to make the analyze command run quickly against commits that it has already analyzed. This would be particularly useful when running the CLI from a CI environment, since most of them support storing cached information between builds.

```mermaid
flowchart LR
    start(analyze start)
    subgraph cache
        prepare
    end
    subgraph git
        clone --> compute-history
        compute-history --> checkout-histories
        checkout-histories --> compute-remaining-histories{{Histories\nRemain?}}
        compute-remaining-histories -->|Yes| checkout-history
        checkout-history --> compute-remaining-histories
        compute-remaining-histories -->|No| history-done(Done)
    end
    
    subgraph bom
        generate(generate start) --> generate-histories

        generate-histories --> generate-remaining-histories{{Histories\nRemain?}}
        generate-remaining-histories -->|Yes| generate-history
        generate-history --> generate-remaining-histories
        generate-remaining-histories -->|No| generate-done(Done)				
    end
    subgraph compute
        libyear
    end
    subgraph persist
        save-to-database
    end
    subgraph output
        create-local-report
    end
    subgraph publish
        send-to-freshli-web
    end
    start --> cache
    cache --> git
    git --> bom
    bom --> compute
    compute --> persist
    compute --> output
    compute --> publish
```

```mermaid
flowchart
    subgraph agent
        subgraph lang
            lang-detect-manifests[detect-manifests]
        end
    end

    subgraph agents
        agents-detect[detect]
    end

    subgraph bom
	generate-history --> detect-all-manifests
        detect-all-manifests --> agents-detect
	detect-all-manifests --> all-manifests-detected{{All\nManifests\nDetected}}
        all-manifests-detected -->|No| lang-detect-manifests
        lang-detect-manifests --> all-manifests-detected
        all-manifests-detected -->|Yes| process-all-manifests
    end
```

```mermaid
flowchart
    subgraph agent
        subgraph lang
            lang-process-manifest[process-manifest]
        end
    end

    subgraph bom
        process-all-manifests --> all-manifests-processed{{All\nManifests\nProcessed}}

        all-manifests-processed -->|No| lang-process-manifest
        lang-process-manifest --> all-manifests-processed
        all-manifests-processed -->|Yes| process-manifests-done(Done)
    end
```

The above graphs will be updated as more commands are identified and added to the pipeline.

The following issues are associated with this epic.
* #49
* #50 
* #51 
* #52 
* #53 
* #54 
* #56
* #57 
* #58
* #59 
* #60 
* #61 
* #62 
* #97

**Comment by mscottford** [comment]
The graph above will be updated as additional commands are created.

**Comment by edwinkortman** [comment]
```mermaid
flowchart
subgraph flow
  A[Command] --> B[Command handler] --> C(Event) --> D(Event Listener) --> A[Command]
end
```

Some rules to this flow:
- A command is just an data object, containing enough information for the handler to do it's job. Typically objects with a small foot print, so just identifiers, and primitive types.
- Handlers can scale horizontally. I could have x workers running handlers to process commands, if one command fails to be processed the others should be able to continue.
- Events are like commands, data objects. 
- Event listeners can spawn a command. It cannot start doing stuff other than that.

```mermaid
flowchart TD
subgraph git

  cloneGitCommand[Clone Git Repository: command] --> 
  cloneGitCommandHandler[Clone Git Repository: command handler] --> 
  cloneGitEvent(Git Repository Was Cloned: event) -->
  cloneGitEventListener(Git Repository Was Cloned: event listener) --> 
  computeHistoryCommand[Compute History: command] --> 
  computeHistoryCommandHandler[Compute History: command handler] -->
  |For each point in history found|pointInGitHistoryFound(Point in Git history found: event) -->
  pointInGitHistoryFoundListener(Point in git history found: event listener) -->
  checkoutHistory[Check out history: command] -->
  checkoutHistoryHandler[Checkout history: command handler]
end
```

### What a command would look like

```php
final class ComputeHistory 
{
      private RepositoryId $repositoryId; 
      public __construct(RepositoryId $repositoryId) 
      {
            $this->repositoryId = $repositoryId;
      }

      public function repositoryId()
      {
            return $this->repositoryId;
      }
}
```

### What an Event would look like
Similar to the Command but the class name is different. It's describing something that has happened instead of describing something you want to make happen.

```php
final class HistoryWasComputed 
{
      private GitCommitId $commitId; 

      public __construct(GitCommitId $commitId) 
      {
            $this->commitId = $commitId;
      }

      public function commitId()
      {
            return $this->commitId;
      }
}
```

### What a Listener would look like

```php
final class HistoryWasComputedListener
{
      public function __invoke(HistoryWasComputed $event)
     {
            $this->commandBus->create(
                  new CheckoutHistoryCommand($event->commitId())
            );
     }
}
```

### What a Command Handler would look like

```php
final class CheckoutHistoryHandler
{
      public function handle(CheckoutHistoryCommand $command)
     {
            // Do the actual handling of stuff so in this example. Checkout the history for a given git commit id. 
     }
}
```

**Comment by mscottford** [comment]
Many of the commands that were specified by this approach have been removed in light of the decision to adopt the approach described in #135. A few commands remain, these are all that are suspected will be needed to assist with working with agents. As such, this epic is going to be considered "complete" and superseded by the effort to use the application engine to implement the CycloneDX processing.
