### ISSUE TITLE
Add `agents verify` command

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#62]
## `agents verify`

Used to test all of the language agents that are available for use. It tests if all the agents are adhering to the contract. e.g. does it have the expected output for `validating-repositories`. 

```
freshli [global options] agents verify [command options] [language-name]
```

**What this command does?**

When no language name is specified, delegates to the `agents detect` to detect each available for agent, and then operates as if the `agents verify` command had been called once for each available language.

When a language is specified invokes the language agent’s `validating-repositories` command to get the urls of a publicly available repositories that the agent can be validated against. Each provided repository is then cloned as a child of `CACHE_ROOT/<lang>/` directory. It is up to the language agent to determine the correct number of repositories to validate against, but the expectation is that at least one repository url is provided for each manifest file format that the language agent knows how to detect and process. If any of the repositories fails to clone, then an error is generated.

For each repository that has been checked out, the language agent’s `detect-manifests` command is invoked. The command output is then validated to ensure that at least one manifest file has been detected. If no manifest files are detected, then then an error is generated.

For each repository, the language agent’s `process-manifests` command is then invoked. It is expected that the output of the command contains the following for each manifest file that was processed:

- manifest file location in the cache tree
- resulting bom file location in the cache tree
- optionally, if a modified manifest file was generated as part of the processing, the location in the cache tree of the original manifest file

If the language agent’s `process-manifests` command does not process the same number of manifests as were detected by the language agent’s `detect-manifests` command, then an error is generated.

If the output of the `process-manifests` command lists files that don’t exist or are empty, then an error is generated.

If the resulting CycloneDX bom file is not a valid JSON-formatted CycloneDX bom file, then an error is generated.

If the any residual modifications to the cloned source code repository are detected after `process-manifests` command has completed, then an error is thrown. This is the same validation that is performed when running the `bom process-all-manifests` command with the `--verify-directories` option.

For each language that this command evaluates, the result of the verification is listed along with the number of repositories that were tested and the amount of time that it took to perform the verification.

Global Options

- `--cache-dir <path>`
    - the location where the `freshli` command will write temporary files as part of it’s processing
    - default value: `$HOME/.freshli`

Command Options

- `--workers`
    - the number of worker processes that should be running at any given time. This defaults to twice the number of CPU cores.
    - default: N+1 where N is the number of cores that are detected in the CPU

**Comment by edwinkortman** [comment]
@donabp I'm cross-posting your questions from Slack. Slack doesn't lend itself well for multiple questions in one thread, and to start multiple threads would be iffy as well. I'll describe a bit about the command first before getting back to your questions.

What we want to achieve with this command is that it'll test the agents if they adhere to the contract expected. So if we can `/path/to/agent process-manifests` does it give the expect output? If I then use that output for the next command, does it work etcetera. 

The current state of our mock agent is very much a happy path agent. So if we call `freshli-agent-mock validating-package-urls` it'll always return package urls. Let's start with building something that verifies the happy paths first, and then we'll continue on to dealing with errors. So:
- Calling `agents verify mock` will identify `freshli-agent-mock` as the agent to verify. This bit uses the AgentsDetector to detect all available agents and selects the right one based off name. 
- `freshli-agent-mock validating-repositories` is then called, this returns a list of repository urls (https://github.com/corgibytes/freshli-cli/blob/main/bin/freshli-agent-mock.rb#L27)
- For each repository url returned, the repository is then cloned into cache. What we do here: https://github.com/corgibytes/freshli-cli/blob/main/Corgibytes.Freshli.Cli/CommandRunners/Git/GitCloneCommandRunner.cs#L19
- Once it's cloned, run `freshli-agent-mock detect-manifests` (https://github.com/corgibytes/freshli-cli/blob/main/bin/freshli-agent-mock.rb#L41)
- Then run `freshli-agent-mock process-manifests`. The output of `process-manifests` has to match the output of `detect-manifests`.
- Then run `freshli-agent-mock validating-package-urls`, this should return at least one row. 

After you have this, we can look at how to deal with errors for when agents aren't working as expected.

**Your questions**
> when cloning how should I know if I clone from the master or main branch? Github has changed from the master branch to the main now but old code bases still use master

The branch is optional. If you clone without passing a branch it'll use whatever is set to the default. 

> what do you mean by validating against these URLs in agent verify? If I can’t clone then it doesn’t work, if I can it’s a valid URL?

Assume everything is working as intended for now, we'll get to the error handling later.

> how do we check that something is a bom file?
> How do we find a cycloneDX file?
> How do you check if the cycloneDX file is a valid file? check if it has JSON at the end of the file?

I grouped these together as a CycloneDX file is a BoM file, but not all BoM files are CycloneDX files. BoM stands for Bill of Materials, it's a list that contains everything needed to build something. This could be a product or a service but software as well. CycloneDX is a format for your Bill of Materials specifically build for software projects.
https://www.investopedia.com/terms/b/bill-of-materials.asp
https://cyclonedx.org/

There's packages out there that can help us with verifying these files. :D But we can look at those later.
https://cyclonedx.org/tool-center/

> How do we check for a manifest file within a cloned repository? (detect-manifests)

We can safely assume the agent knows how to detect that. What I'm saying is that's going to be the challenge when we build the agents. :p
