### ISSUE TITLE
Document project style guidelines for C#

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#82]
Document the style guidelines for the project. Inspired by a [recent code review](https://github.com/corgibytes/freshli-cli/pull/81#pullrequestreview-979136269).

Where possible, enable Roslyn analyzers that help enforce the project style.

**Comment by CodeMouse92** [comment]
Be advised, my next PR will be adding [SonarLint](https://www.sonarlint.org/); that may be useful for some things.

**Comment by mscottford** [comment]
This has been mostly done. Or at least done enough for now.
